#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };


//홍준수정 상호작용전용 오브젝트 추가 OBJ_INTERACTION 
enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_INTERACTION,OBJ_TEMP, OBJ_SHIELD, OBJ_END };